#resolver: lts-8.3
resolver: lts-7.19
#compiler: ghcjs-0.2.1.9008003_ghc-8.0.2
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
        ghcjs-0.2.1.9007019_ghc-8.0.1:
           #url: /Users/Tom/Projects/prepare-ghcjs/testunpack/ghc-8.0-2017-02-28-lts-8.3-9008003.tar.gz
            url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
            sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

packages:
- .
- /Users/Tom/Projects/react-flux-servant/
- /Users/Tom/Projects/react-flux/

extra-deps:
